# Kafka AI Agent Configuration

environments:
  dev:
    registry_url: "${SCHEMA_REGISTRY_DEV_URL}"
    context: "development"
    compatibility: "BACKWARD"
  staging:
    registry_url: "${SCHEMA_REGISTRY_STAGING_URL}"
    context: "staging"
    compatibility: "BACKWARD"
  production:
    registry_url: "${SCHEMA_REGISTRY_PROD_URL}"
    context: "production"
    compatibility: "FULL"

mcp_server:
  host: "${MCP_SERVER_HOST}"
  port: ${MCP_SERVER_PORT}
  
llm_providers:
  primary: "anthropic"  # or "openai", "google", "ollama"
  fallback: "openai"
  model_settings:
    anthropic:
      model: "claude-3-opus-20240229"
      max_tokens: 2000
    openai:
      model: "gpt-4-turbo"
      temperature: 0.7
    google:
      model: "gemini-pro"
  
features:
  auto_documentation: true
  breaking_change_prevention: true
  evolution_suggestions: true
  natural_language_queries: true
  monitoring_interval: 60  # seconds

monitoring:
  enabled: true
  alert_channels:
    - slack
    - email
  thresholds:
    schema_changes_per_hour: 10
    failed_registrations: 3

logging:
  level: "INFO"
  format: "json"
  file: "logs/kafka-ai-agent.log"